registered email:- md.rafiur.rahman.saikat@gmail.com

In [ ]:
# You must run this code and use this dataset for all questions

import numpy as np
import pandas as pd

np.random.seed(24)

num_employees = 50  # you can increase this if needed

# Employee data
emp_ids = np.arange(101, 101 + num_employees)
emp_ages = np.random.randint(20, 55, num_employees)
emp_income = np.random.randint(35000, 95000, num_employees)

# Fixed set of roles (repetition allowed)
roles_list = [
    "HR Manager",
    "Software Developer",
    "Accountant",
    "Marketing Executive",
    "Sales Executive",
    "Backend Developer",
    "HR Executive",
    "Financial Analyst",
    "Digital Marketer",
    "Operations Manager",
]

emp_roles = np.random.choice(roles_list, num_employees)

# Create DataFrame
data = pd.DataFrame(
    {
        "emp_id": emp_ids,
        "emp_age": emp_ages,
        "emp_salary": emp_income,
        "role": emp_roles,
    }
)

# Save dataset
data.to_csv("staff_data.csv", index=False)

**Q1.**
Use  NumPy arrays from the emp_ages and emp_salary columns.
 Print both arrays and display:
*  data type
*  number of dimensions
*  shape
*  total number of elements

In [ ]:
print("Age Array:\n", emp_ages)
print("Data type  of Age Array:", emp_ages.dtype)
print("Dimensions of Age Array:", emp_ages.ndim)
print("Shape      of Age Array:", emp_ages.shape)
print("Elements   of Age Array:", emp_ages.size)

print("\nSalary Array:\n", emp_income)
print("Data type  of Salary Array:", emp_income.dtype)
print("Dimensions of Salary Array:", emp_income.ndim)
print("Shape      of Salary Array:", emp_income.shape)
print("Elements   of Salary Array:", emp_income.size)

Age Array:
 [54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]
Data type  of Age Array: int64
Dimensions of Age Array: 1
Shape      of Age Array: (50,)
Elements   of Age Array: 50

Salary Array:
 [51725 38495 35452 82295 72187 58915 76159 92864 76155 90494 68641 48079
 56879 83682 94722 91041 48899 68744 63187 74146 75641 47678 76760 78354
 60584 79898 59682 71888 51086 73700 82550 71447 76100 72269 73314 87428
 94427 84188 52013 63326 44396 59500 55523 58602 90794 41061 82331 73048
 59727 50398]
Data type  of Salary Array: int64
Dimensions of Salary Array: 1
Shape      of Salary Array: (50,)
Elements   of Salary Array: 50

**Q2.**
Using NumPy functions:

* Find the maximum and minimum salary
* Calculate the average salary
* Calculate the average age
* Print all results.

In [473]:
print("Max Salary:", np.max(emp_income))
print("Min Salary:", np.min(emp_income))
print("Avg Salary:", np.mean(emp_income))
print("Avg Age   :", np.mean(emp_ages))

Max Salary: 94722
Min Salary: 35452
Avg Salary: 68409.48
Avg Age   : 35.44

**Q3.**

From the emp_ages array:

**Extract employees who:**
* are aged between 25 and 40, 

AND 

**Emp_salary : 
* have salary greater than 50,000**
* Then : Print the filtered values
* Count how many employees satisfy this condition

In [ ]:
age_25_to_40 = emp_ages[(emp_ages >= 25) & (emp_ages <= 40)]
salary_gt_50k = emp_income[(emp_income > 50000)]
total = np.count_nonzero(age_25_to_40) + np.count_nonzero(salary_gt_50k)


print("Filtered ages :\n", age_25_to_40)
print("\nAge Count     :", np.count_nonzero(age_25_to_40))

print("\nFiltered salaries :\n", salary_gt_50k)
print("\nSalaries Count      :", np.count_nonzero(salary_gt_50k))
print("\n\nTotal Count     :", total)

Filtered ages :
 [37 37 35 38 31 35 29 38 27 32 26 37 26 30 30 27 25 39 31]

Age Count     : 19
Filtered salaries :
 [51725 82295 72187 58915 76159 92864 76155 90494 68641 56879 83682 94722
 91041 68744 63187 74146 75641 76760 78354 60584 79898 59682 71888 51086
 73700 82550 71447 76100 72269 73314 87428 94427 84188 52013 63326 59500
 55523 58602 90794 82331 73048 59727 50398]

Salaries Count      : 43


Total Count     : 62

**Q4.**
Create a new NumPy array where each employee’s age is adjusted based on:
* Add 4 years if age is less than the average age
* Add 2 years if age is greater than or equal to the average age

***Do NOT modify the original array.***

Print:
* original array
* updated array
* average age used for condition

In [ ]:
average_age = np.mean(emp_ages)
adjusted_ages = np.where(emp_ages < average_age, emp_ages + 4, emp_ages + 2)

print("Original Array:\n", emp_ages)
print("\nUpdated Array:\n", adjusted_ages)
print("\nAverage Age:", average_age)

Original Array:
 [54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]

Updated Array:
 [56 27 24 45 39 39 25 39 28 40 35 39 33 40 31 47 53 50 24 36 53 55 25 30
 55 39 30 25 47 34 24 49 55 55 27 28 25 34 31 29 41 24 49 43 26 54 44 56
 35 52]

Average Age: 35.44

**Q5.**

Using NumPy:
* Assume all salaries of **Tech roles** increase by **8%**
* Calculate the **new total salary expense**
* Find the **overall increase in expense** after the raise

**Print both old and new totals along with the difference.**

In [476]:
roles = data["role"]
salary = data["emp_salary"]
data

    emp_id  emp_age  emp_salary                 role
0      101       54       51725           HR Manager
1      102       23       38495           Accountant
2      103       20       35452   Operations Manager
3      104       43       82295     Digital Marketer
4      105       37       72187    Backend Developer
5      106       37       58915           HR Manager
6      107       21       76159    Backend Developer
7      108       35       92864      Sales Executive
8      109       24       76155      Sales Executive
9      110       38       90494         HR Executive
10     111       31       68641    Backend Developer
11     112       35       48079  Marketing Executive
12     113       29       56879      Sales Executive
13     114       38       83682   Operations Manager
14     115       27       94722     Digital Marketer
15     116       45       91041    Financial Analyst
16     117       51       48899      Sales Executive
17     118       48       68744   Operations Manager
18     119       20       63187   Software Developer
19     120       32       74146    Backend Developer
20     121       51       75641      Sales Executive
21     122       53       47678      Sales Executive
22     123       21       76760           Accountant
23     124       26       78354   Software Developer
24     125       53       60584         HR Executive
25     126       37       79898   Operations Manager
26     127       26       59682     Digital Marketer
27     128       21       71888         HR Executive
28     129       45       51086   Software Developer
29     130       30       73700           Accountant
30     131       20       82550      Sales Executive
31     132       47       71447  Marketing Executive
32     133       53       76100     Digital Marketer
33     134       53       72269    Backend Developer
34     135       23       73314   Software Developer
35     136       24       87428   Software Developer
36     137       21       94427      Sales Executive
37     138       30       84188           Accountant
38     139       27       52013           HR Manager
39     140       25       63326      Sales Executive
40     141       39       44396  Marketing Executive
41     142       20       59500     Digital Marketer
42     143       47       55523         HR Executive
43     144       41       58602           Accountant
44     145       22       90794         HR Executive
45     146       52       41061           HR Manager
46     147       42       82331   Software Developer
47     148       54       73048   Software Developer
48     149       31       59727     Digital Marketer
49     150       50       50398  Marketing Executive

In [ ]:
import numpy as np

a = np.arange(10)

np.where((a > 3) & (a <= 7), a, a * 10)

array([ 0, 10, 20, 30,  4,  5,  6,  7, 80, 90])

In [478]:
roles = np.array(data["role"])
salary = np.array(data["emp_salary"])

increased_salary = np.where(
    (
        (roles == "Software Developer")
        | (roles == "Backend Developer")
        | (roles == "Digital Marketer")
    ),
    salary * (1 + 8 / 100),
    salary,
)

old_total = np.sum(salary)
new_total = np.sum(increased_salary)
difference = new_total - old_total

# print(type(roles))
# print(type(salary))
# print(roles.ndim)
# print(salary.ndim)


print("Old Total Salary:", old_total)
print("New Total Salary:", new_total)
print("Increased Expense:", difference)

Old Total Salary: 3420474
New Total Salary: 3524808.08
Increased Expense: 104334.08000000007

**Q6.**

Load the staff_data.csv file into a Pandas DataFrame.
* Display the first 3 rows
* Show dataset information using .info()
* Display summary statistics using .describe()

In [518]:
df = pd.read_csv("staff_data.csv")
df.head(3)
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      50 non-null     int64
 1   emp_age     50 non-null     int64
 2   emp_salary  50 non-null     int64
 3   role        50 non-null     str
dtypes: int64(3), str(1)
memory usage: 1.7 KB

          emp_id    emp_age    emp_salary
count   50.00000  50.000000     50.000000
mean   125.50000  35.440000  68409.480000
std     14.57738  11.768446  15727.122334
min    101.00000  20.000000  35452.000000
25%    113.25000  24.250000  57309.750000
50%    125.50000  35.000000  72037.500000
75%    137.75000  46.500000  79512.000000
max    150.00000  54.000000  94722.000000

**Q7.**
Filter the dataset to include only:
* emp_id, emp_age, role

**Then:**
* Select employees whose age is between 25 and 40
* Sort them by emp_id
* Display the last 3 rows of the result

In [ ]:
filtered_df = df[["emp_id", "emp_age", "role"]]
selected_employee = filtered_df[
    (filtered_df["emp_age"] >= 25) & (filtered_df["emp_age"] <= 40)
]
sorted_df = selected_employee.sort_values("emp_id", ascending=True)
sorted_df.tail(3)

    emp_id  emp_age                 role
39     140       25      Sales Executive
40     141       39  Marketing Executive
48     149       31     Digital Marketer

**Q8.**

Filter the DataFrame to show only employees working in the **"HR" **role.

* Print the filtered data
* Show the total number of HR employees

In [ ]:
df

    emp_id  emp_age  emp_salary                 role
0      101       54       51725           HR Manager
1      102       23       38495           Accountant
2      103       20       35452   Operations Manager
3      104       43       82295     Digital Marketer
4      105       37       72187    Backend Developer
5      106       37       58915           HR Manager
6      107       21       76159    Backend Developer
7      108       35       92864      Sales Executive
8      109       24       76155      Sales Executive
9      110       38       90494         HR Executive
10     111       31       68641    Backend Developer
11     112       35       48079  Marketing Executive
12     113       29       56879      Sales Executive
13     114       38       83682   Operations Manager
14     115       27       94722     Digital Marketer
15     116       45       91041    Financial Analyst
16     117       51       48899      Sales Executive
17     118       48       68744   Operations Manager
18     119       20       63187   Software Developer
19     120       32       74146    Backend Developer
20     121       51       75641      Sales Executive
21     122       53       47678      Sales Executive
22     123       21       76760           Accountant
23     124       26       78354   Software Developer
24     125       53       60584         HR Executive
25     126       37       79898   Operations Manager
26     127       26       59682     Digital Marketer
27     128       21       71888         HR Executive
28     129       45       51086   Software Developer
29     130       30       73700           Accountant
30     131       20       82550      Sales Executive
31     132       47       71447  Marketing Executive
32     133       53       76100     Digital Marketer
33     134       53       72269    Backend Developer
34     135       23       73314   Software Developer
35     136       24       87428   Software Developer
36     137       21       94427      Sales Executive
37     138       30       84188           Accountant
38     139       27       52013           HR Manager
39     140       25       63326      Sales Executive
40     141       39       44396  Marketing Executive
41     142       20       59500     Digital Marketer
42     143       47       55523         HR Executive
43     144       41       58602           Accountant
44     145       22       90794         HR Executive
45     146       52       41061           HR Manager
46     147       42       82331   Software Developer
47     148       54       73048   Software Developer
48     149       31       59727     Digital Marketer
49     150       50       50398  Marketing Executive

In [ ]:
# hr_list=[]
# for hr in df.itertuples(index=False):
#     if "HR" in hr.role:
#         hr_list.append(hr)
# hr_df=pd.DataFrame(hr_list)
# print("\nTotal number of HR employees :",hr_df.count().role)
# hr_df

hr_df = df["role"].isin(["HR Manager", "HR Executive"])
print("\nTotal number of HR employees :", df.loc[hr_df].count().emp_id)
df.loc[hr_df]

Total number of HR employees : 9

,emp_id,emp_age,emp_salary,role,prev_salary,new_salary,increase_of_salary
0,101,54,51725,HR Manager,51725.0,54311.25,2586.25
5,106,37,58915,HR Manager,58915.0,61860.75,2945.75
9,110,38,90494,HR Executive,90494.0,95018.7,4524.7
24,125,53,60584,HR Executive,60584.0,63613.2,3029.2
27,128,21,71888,HR Executive,71888.0,75482.4,3594.4
38,139,27,52013,HR Manager,52013.0,54613.65,2600.65
42,143,47,55523,HR Executive,55523.0,58299.15,2776.15
44,145,22,90794,HR Executive,90794.0,95333.7,4539.7
45,146,52,41061,HR Manager,41061.0,43114.05,2053.05

**Q9.**

Sort the DataFrame by:
* emp_age (ascending)
* and then by emp_salary (descending)

Display the top 5 employees after sorting, including:
* emp_id
* role
* emp_salary

In [483]:
"""
emp_id	role	emp_salary
14	115	Digital Marketer	94722
36	137	Sales Executive	94427
7	108	Sales Executive	92864
15	116	Financial Analyst	91041
44	145	HR Executive	90794
"""

sorted_by_age = df.sort_values(by=["emp_age"], ascending=True)
sorted_by_salary = sorted_by_age.sort_values(by=["emp_salary"], ascending=False)
print(sorted_by_salary[["emp_id", "role", "emp_age", "emp_salary"]].head(5))

sorted_df = df.sort_values(by=["emp_age", "emp_salary"], ascending=[True, False])
sorted_df[["emp_id", "role", "emp_age", "emp_salary"]].head(5)

    emp_id               role  emp_age  emp_salary
14     115   Digital Marketer       27       94722
36     137    Sales Executive       21       94427
7      108    Sales Executive       35       92864
15     116  Financial Analyst       45       91041
44     145       HR Executive       22       90794

    emp_id                role  emp_age  emp_salary
30     131     Sales Executive       20       82550
18     119  Software Developer       20       63187
41     142    Digital Marketer       20       59500
2      103  Operations Manager       20       35452
36     137     Sales Executive       21       94427

**Q10.**

Using .loc:
* Increase salary by **12% for "Software Developer" and "Backend Developer"**
* Increase salary by **5% for all other roles**

Then:

* Print the dataframe that includes  **role , previous_salary , new_salary , increase_of_salary**

In [ ]:
df["prev_salary"] = df["emp_salary"].astype("Float64")

dev_df = df["role"].isin(["Software Developer", "Backend Developer"])

df.loc[:, "new_salary"] = df["prev_salary"] * 1.05
df.loc[dev_df, "new_salary"] = df.loc[dev_df, "prev_salary"] * 1.12


df["increase_of_salary"] = df["new_salary"] - df["prev_salary"]


df[["role", "prev_salary", "new_salary", "increase_of_salary"]]

                   role  prev_salary  new_salary  increase_of_salary
0            HR Manager      51725.0    54311.25             2586.25
1            Accountant      38495.0    40419.75             1924.75
2    Operations Manager      35452.0     37224.6              1772.6
3      Digital Marketer      82295.0    86409.75             4114.75
4     Backend Developer      72187.0    80849.44             8662.44
5            HR Manager      58915.0    61860.75             2945.75
6     Backend Developer      76159.0    85298.08             9139.08
7       Sales Executive      92864.0     97507.2              4643.2
8       Sales Executive      76155.0    79962.75             3807.75
9          HR Executive      90494.0     95018.7              4524.7
10    Backend Developer      68641.0    76877.92             8236.92
11  Marketing Executive      48079.0    50482.95             2403.95
12      Sales Executive      56879.0    59722.95             2843.95
13   Operations Manager      83682.0     87866.1              4184.1
14     Digital Marketer      94722.0     99458.1              4736.1
15    Financial Analyst      91041.0    95593.05             4552.05
16      Sales Executive      48899.0    51343.95             2444.95
17   Operations Manager      68744.0     72181.2              3437.2
18   Software Developer      63187.0    70769.44             7582.44
19    Backend Developer      74146.0    83043.52             8897.52
20      Sales Executive      75641.0    79423.05             3782.05
21      Sales Executive      47678.0     50061.9              2383.9
22           Accountant      76760.0     80598.0              3838.0
23   Software Developer      78354.0    87756.48             9402.48
24         HR Executive      60584.0     63613.2              3029.2
25   Operations Manager      79898.0     83892.9              3994.9
26     Digital Marketer      59682.0     62666.1              2984.1
27         HR Executive      71888.0     75482.4              3594.4
28   Software Developer      51086.0    57216.32             6130.32
29           Accountant      73700.0     77385.0              3685.0
30      Sales Executive      82550.0     86677.5              4127.5
31  Marketing Executive      71447.0    75019.35             3572.35
32     Digital Marketer      76100.0     79905.0              3805.0
33    Backend Developer      72269.0    80941.28             8672.28
34   Software Developer      73314.0    82111.68             8797.68
35   Software Developer      87428.0    97919.36            10491.36
36      Sales Executive      94427.0    99148.35             4721.35
37           Accountant      84188.0     88397.4              4209.4
38           HR Manager      52013.0    54613.65             2600.65
39      Sales Executive      63326.0     66492.3              3166.3
40  Marketing Executive      44396.0     46615.8              2219.8
41     Digital Marketer      59500.0     62475.0              2975.0
42         HR Executive      55523.0    58299.15             2776.15
43           Accountant      58602.0     61532.1              2930.1
44         HR Executive      90794.0     95333.7              4539.7
45           HR Manager      41061.0    43114.05             2053.05
46   Software Developer      82331.0    92210.72             9879.72
47   Software Developer      73048.0    81813.76             8765.76
48     Digital Marketer      59727.0    62713.35             2986.35
49  Marketing Executive      50398.0     52917.9              2519.9